include ../../makefile.conf

JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

CLASSES = \
	SandPointer.java\
	SandPointerThread.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
	$(RM) *.class
